Pull network info from NETWORK_LIST json in resourceview
vmware-archive/terraform-provider-vra7 pull request #30
Opened 2019-09-06 07:03 UTC by cars

This is a possible solution/workaround to #16 that utilizes the NETWORK_LIST data map as suggested by @hobovirtual. It works for both privileged (Tenant Admin) and non-privileged users, as well as supporting cases where there might be multiple interfaces/NICs.  It doesn't use the ip_address field but fields more similar to the vRA custom properties one would use to specify the settings in a request.   In the case of a blueprint with a component called 'VM' with two NICs the _resource_configuration_ block would look something like: 
```terraform
 resource_configuration = {
    "VM.cpu" = 2
    "VM.ip_address" = ""
    "VM.name" = ""
    "VM.Network0.IPAddress" = ""
    "VM.Network0.MACAddress" = ""
    "VM.Network0.Name" = ""
    "VM.Network1.IPAddress" = ""
    "VM.Network1.MACAddress" = ""
    "VM.Network1.Name" = ""

  }
```

so using  a count of 2 in the resource definition and the following output: 

```terraform
# Or, print the whole thing:
output "Machine_Info" {
  value = vra7_deployment.test.*.resource_configuration
}
```

would yield something like:
```terraform
Machine_Info = [
  {
    "VM.Network0.IPAddress" = "10.0.3.131"
    "VM.Network0.MACAddress" = "00:50:56:84:e5:d3"
    "VM.Network0.Name" = "Public 3"
    "VM.Network1.IPAddress" = "10.0.4.102"
    "VM.Network1.MACAddress" = "00:50:56:84:8c:2e"
    "VM.Network1.Name" = "Public 4"
    "VM.cpu" = "2"
    "VM.ip_address" = ""
    "VM.name" = "K8S0305"
  },
  {
    "VM.Network0.IPAddress" = "10.0.3.130"
    "VM.Network0.MACAddress" = "00:50:56:84:d4:37"
    "VM.Network0.Name" = "Public 3"
    "VM.Network1.IPAddress" = "10.0.4.101"
    "VM.Network1.MACAddress" = "00:50:56:84:57:7e"
    "VM.Network1.Name" = "Public 4"
    "VM.cpu" = "2"
    "VM.ip_address" = ""
    "VM.name" = "K8S0306"
  },
]
```

2019-09-06 14:00 UTC, markpeek requested changes
In general this looks good. A couple of tweaks needed. Also, I'd like @Prativa20 to look at this change and approve. Thanks!

2019-09-06 14:00 UTC, markpeek commented on build.cmd
> +cd S:\gosrc\src\github.com\cars\terraform-provider-vra7-1
The build.cmd script crept in even thought you had .gitignore

2019-09-06 14:00 UTC, markpeek commented on go.mod
> +go 1.13
Likely don't want to introduce a 1.13 dependency quite yet. Could you remove go.mod?

2019-09-06 16:36 UTC, cars commented
@markpeek  I think I made the changes correctly

2019-09-12 20:50 UTC, Prativa20 approved these changes
Looks good to me!

2019-09-16 15:10 UTC, markpeek approved these changes

2019-09-16 15:11 UTC, merged